video:
  input_dir: "feels"  # 输入视频目录
  output:
    is_text: True
    is_audio: True
    is_subtitle: True
    output_dir: "output/feels"  # 主输出目录
  extensions:  # 支持的视频格式
    - ".mp4"
    - ".avi"
    - ".mkv"
    - ".mov"
    - ".wmv"
whisper:
  model: "turbo"  # whisper模型类型


